import carticon from '../assets/carticon.jpg'
import filltericon from '../assets/filtter icon.png'
import gt1 from '../assets/gt1.jpg'
import k1 from '../assets/k1.png'
import k2 from '../assets/k2.jpg'
import k3 from '../assets/k3.jpg'
import kt1 from '../assets/kt1.jpg'
import kt2 from '../assets/kt2.jpg'
import kt3 from '../assets/kt3.png'
import kt4 from '../assets/kt4.jpg'
import logo from '../assets/logo.png'
import p1 from '../assets/p1.jpg'
import p2 from '../assets/p2.jpg'
import p3 from '../assets/p3.webp'
import p4 from '../assets/p4.jpg'
import p5 from '../assets/p5.jpg'
import p6 from '../assets/p6.jpg'
import profileicon from '../assets/profileicon.png'
import s1 from '../assets/s1.jpg'
import s2 from '../assets/s2.jpg'
import s3 from '../assets/s3.jpg'
import s4 from '../assets/s4.jpg' 
import s5 from '../assets/s5.jpg'
import seachicon from  '../assets/searchicon.png'
import T from '../assets/T.png'
import T2 from '../assets/T2.png'
import T10 from '../assets/T10.jpg'
import T3 from '../assets/T3.png'
import T4 from '../assets/T4.jpg'
import T9 from '../assets/T4.png'
import T5 from '../assets/T5.png'
import T6 from '../assets/T6.jpg'
import T7 from '../assets/T7.jpg'
import T8 from '../assets/T8.jpg'
import w1 from '../assets/w1.jpg'
import w2 from '../assets/w3.png'
import w3 from '../assets/w3.png'
import w4 from '../assets/w4.png'
import w5 from '../assets/w5.png'
import w6 from '../assets/w6.jpg'
import w7 from '../assets/w7.png'
import w8 from '../assets/w8.jpg'
import w9 from '../assets/w9.jpg'
import star from '../assets/star.jpeg'
import dullstar from '../assets/blankstar.jpeg'
import serach from '../assets/searchicon.png'
import heart from '../assets/hearticon.jpeg'
import backicon from '../assets/backicon.jpeg'
import Return from '../assets/returnpolicyicon.png';
import chang from '../assets/changeserviceicon.png';
import customer from '../assets/customersupporticon.png'
import dropdown from  '../assets/dropdownicon.jpeg'
import { Cross } from 'hamburger-react'
export const assets = {
    carticon,filltericon,gt1,k1,k2,k3,kt1,kt2,kt3,kt4,logo,p1,p2,p3,p4,p5,p6,profileicon,
    s1,s2,s3,s4,s5,seachicon,T,T10,T2,T3,T4,T9,T5,T6,T8,T7,w1,w2,w3,w4,w5,w6,w7,w8,w9,heart,backicon,chang,Return,customer,
    dropdown,Cross,star,dullstar,serach
} 